artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2023-12-12/data/listings.csv.gz
  local_data_file: artifacts/data_ingestion/listings.csv.gz
  local_data_file_csv: artifacts/data_ingestion/listings.csv
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_train_path: "artifacts/data_ingestion/train.csv"
  data_val_path: "artifacts/data_ingestion/val.csv"
  data_test_path: "artifacts/data_ingestion/test.csv"
  transformer: artifacts/data_transformation/data_transformer.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  data_X_train_path: "artifacts/data_transformation/X_train.joblib"
  data_y_train_path: "artifacts/data_transformation/y_train.joblib" 
  data_X_val_path: "artifacts/data_transformation/X_val.joblib"
  data_y_val_path: "artifacts/data_transformation/y_val.joblib"
  best_model: "artifacts/model_trainer/best_model.pkl"
  best_model_params: "artifacts/model_trainer/best_model_params.pkl"
  best_model_rmse: "artifacts/model_trainer/best_model_rmse.pkl"


